[package]
name = "ale_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.44.2", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
